name: PR Build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.1
      - name: Lint
        run: make lint
  build-and-test-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Choose tags corresponding to the version of Kind being used.
        # https://hub.docker.com/r/kindest/node/tags
        k8s-version:
          - v1.25.3
          - v1.24.7
          - v1.23.13
          - v1.22.15
          - v1.21.14
          - v1.20.15
          - v1.19.16
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: make docker-build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: make docker-build
      - name: Run integration tests
        run: K8S_VERSION=${{ matrix.k8s-version }} test/run.sh
