name: PR Build
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Lint
        run: make lint
  build-and-test-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Any tag here
        # https://hub.docker.com/r/kindest/node/tags
        k8s-version:
          - v1.23.1
          - v1.22.4
          - v1.21.1
          - v1.20.7
          - v1.19.11
          - v1.18.19
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: make docker-build
      - name: Run integration tests
        run: K8S_VERSION=${{ matrix.k8s-version }} test/run.sh
